final List<String> dailyFacts = [
  "A day on Venus is longer than a year on Venus.",
  "Saturn could float in water because it’s mostly gas.",
  "Neutron stars are so dense that a teaspoon of their material weighs as much as Mount Everest.",
  "One million Earths could fit inside the Sun.",
  "Jupiter has the shortest day of all the planets, lasting less than 10 hours.",
  "There are more stars in the universe than grains of sand on Earth.",
  "The footprints left on the Moon will remain for millions of years.",
  "The Great Red Spot on Jupiter is a storm that has lasted for at least 350 years.",
  "A year on Mercury is just 88 Earth days long.",
  "Pluto was reclassified from a planet to a dwarf planet in 2006.",
  "Light from the Sun takes about 8 minutes and 20 seconds to reach Earth.",
  "Uranus rotates on its side, making it unique among the planets.",
  "The hottest planet in our solar system is Venus, not Mercury.",
  "Comets are often called “dirty snowballs” because they’re made of ice, dust, and rock.",
  "The Milky Way galaxy is estimated to contain over 100 billion planets.",
  "Black holes are so dense that not even light can escape them.",
  "The first human in space was Yuri Gagarin in 1961.",
  "The Moon is slowly drifting away from Earth at about 3.8 cm per year.",
  "The International Space Station travels at 28,000 km/h around Earth.",
  "There are mountains on Mars that are three times taller than Mount Everest.",
  "A day on Mars is about 24 hours and 37 minutes.",
  "Space is completely silent because there is no air to carry sound.",
  "Jupiter’s moon Ganymede is the largest moon in the solar system.",
  "Mercury has no atmosphere to protect it from meteors.",
  "The rings of Saturn are mostly made of ice and dust.",
  "The Sun accounts for 99.86% of the mass in the solar system.",
  "Venus is the brightest planet in our night sky.",
  "Astronauts grow taller in space because of reduced gravity.",
  "Neptune has the strongest winds in the solar system, reaching 2,100 km/h.",
  "It takes the Sun about 225 million years to orbit the center of the Milky Way."
];
